# Generated by Django 2.0.2 on 2018-07-26 10:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('authentication', '0001_initial'),
        ('books', '0001_initial'),
        ('posts', '0001_initial'),
        ('file_store', '0001_initial'),
        ('meta_info', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='cover_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='album_covers+', to='file_store.Image', verbose_name='Cover Image'),
        ),
        migrations.AddField(
            model_name='profile',
            name='images',
            field=models.ManyToManyField(blank=True, related_name='_profile_images_+', to='file_store.Image', verbose_name='Images'),
        ),
        migrations.AddField(
            model_name='profile',
            name='meta_info',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='profiles+', to='meta_info.MetaInfo', verbose_name='Meta data'),
        ),
        migrations.AddField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AddField(
            model_name='invitation',
            name='meta_info',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='invitation_meta+', to='meta_info.MetaInfo', verbose_name='Invitation meta data'),
        ),
        migrations.AddField(
            model_name='invitation',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='authentication.Profile'),
        ),
        migrations.AddField(
            model_name='invitation',
            name='profile_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='invitations', to='authentication.Profile', verbose_name='Profile Invited'),
        ),
        migrations.AddField(
            model_name='invitation',
            name='token',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='invitations+', to='authentication.Token', verbose_name='Verified domain token'),
        ),
        migrations.AddField(
            model_name='contactmethod',
            name='meta_info',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='contacts+', to='meta_info.MetaInfo', verbose_name='Meta data'),
        ),
        migrations.AddField(
            model_name='circlesetting',
            name='circle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='settings', to='authentication.Circle', verbose_name='Settings for Circle'),
        ),
        migrations.AddField(
            model_name='circlesetting',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='_circlesetting_tags_+', to='meta_info.Tag', verbose_name='Tags'),
        ),
        migrations.AddField(
            model_name='circle',
            name='contacts',
            field=models.ManyToManyField(related_name='_circle_contacts_+', to='authentication.ContactMethod', verbose_name='Contact Methods'),
        ),
        migrations.AddField(
            model_name='circle',
            name='cover_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='album_covers+', to='file_store.Image', verbose_name='Cover Image'),
        ),
        migrations.AddField(
            model_name='circle',
            name='images',
            field=models.ManyToManyField(blank=True, related_name='_circle_images_+', to='file_store.Image', verbose_name='Images'),
        ),
        migrations.AddField(
            model_name='circle',
            name='invites',
            field=models.ManyToManyField(related_name='_circle_invites_+', to='authentication.Invitation', verbose_name='Invitations'),
        ),
        migrations.AddField(
            model_name='circle',
            name='meta_info',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='circles_meta+', to='meta_info.MetaInfo', verbose_name='Circles meta data'),
        ),
        migrations.AddField(
            model_name='circle',
            name='reading_list',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='circles', to='books.ReadingList', verbose_name='Reading List'),
        ),
        migrations.AddField(
            model_name='author',
            name='contacts',
            field=models.ManyToManyField(related_name='_author_contacts_+', to='authentication.ContactMethod', verbose_name='Contact Methods'),
        ),
        migrations.AddField(
            model_name='author',
            name='cover_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='album_covers+', to='file_store.Image', verbose_name='Cover Image'),
        ),
        migrations.AddField(
            model_name='author',
            name='emotes',
            field=models.ManyToManyField(blank=True, related_name='_author_emotes_+', to='posts.Emote', verbose_name='Emotes'),
        ),
        migrations.AddField(
            model_name='author',
            name='images',
            field=models.ManyToManyField(blank=True, related_name='_author_images_+', to='file_store.Image', verbose_name='Images'),
        ),
        migrations.AddField(
            model_name='author',
            name='meta_info',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='authors+', to='meta_info.MetaInfo', verbose_name='Meta data'),
        ),
        migrations.AddField(
            model_name='author',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='pen_names', to='authentication.Profile', verbose_name='Profile'),
        ),
    ]
