# Generated by Django 2.0.2 on 2018-04-27 10:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0001_initial'),
        ('meta_info', '0001_initial'),
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='circle',
            name='reading_list',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='circles', to='books.ReadingList', verbose_name='Reading List'),
        ),
        migrations.AddField(
            model_name='authorcontactmethod',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='contacts', to='authentication.Author', verbose_name='Author'),
        ),
        migrations.AddField(
            model_name='authorcontactmethod',
            name='meta_info',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='contacts+', to='meta_info.MetaInfo', verbose_name='Meta data'),
        ),
        migrations.AddField(
            model_name='author',
            name='meta_info',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='profiles+', to='meta_info.MetaInfo', verbose_name='Meta data'),
        ),
        migrations.AlterUniqueTogether(
            name='invitation',
            unique_together={('profile', 'profile_to', 'circle')},
        ),
        migrations.AlterUniqueTogether(
            name='author',
            unique_together={('name_title', 'name_family')},
        ),
    ]
