# Generated by Django 2.0.2 on 2018-07-05 16:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('books', '0001_initial'),
        ('authentication', '0001_initial'),
        ('meta_info', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='circle',
            name='reading_list',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='circles', to='books.ReadingList', verbose_name='Reading List'),
        ),
        migrations.AddField(
            model_name='author',
            name='contacts',
            field=models.ManyToManyField(related_name='_author_contacts_+', to='authentication.ContactMethod', verbose_name='Contact Methods'),
        ),
        migrations.AddField(
            model_name='author',
            name='meta_info',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='authors+', to='meta_info.MetaInfo', verbose_name='Meta data'),
        ),
        migrations.AddField(
            model_name='author',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='pen_names', to='authentication.Profile', verbose_name='Profile'),
        ),
        migrations.AlterUniqueTogether(
            name='invitation',
            unique_together={('profile', 'profile_to')},
        ),
    ]
