# Generated by Django 2.0.2 on 2018-04-25 12:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0001_initial'),
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='circle',
            name='reading_list',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='circles', to='books.ReadingList', verbose_name='Reading List'),
        ),
        migrations.AlterUniqueTogether(
            name='invitation',
            unique_together={('profile', 'profile_to', 'circle')},
        ),
    ]
